server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: integrador_serie
      username: admin
      password: admin
      database: integrador_serie
      port: 27017
      host: mongodb 

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Serie service
